# Generated by Django 2.0.5 on 2018-05-28 18:14

from django.db import migrations, models
import producto.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=500)),
                ('categoria', models.CharField(choices=[('CH', 'Chaqueta'), ('CA', 'Camiseta'), ('PA', 'Pantalon'), ('AC', 'Accesorio')], default='CH', max_length=2)),
                ('talla', models.CharField(blank=True, choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='L', max_length=5, null=True)),
                ('imagen', models.ImageField(null=True, upload_to=producto.models.producto_image)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
